version: '3'
services:
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    # ports:
    #   - "27017:27017" # Map MongoDB port to the host
  node-app:
    restart: on-failure
    build: .
    ports:
      - "4000:4000"
    # environment:
    #   - name=value
    env_file:
      - ./.env