version: '3'

networks:
    app-tier:
      driver: bridge

services:
  node-app:
    networks:
      - app-tier
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    # environment:
    #   - name=value
    env_file:
      - ./.env
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - 27017:27017
    networks:
      - app-tier

